### PR TITLE
Vaccination report

### PR DESCRIPTION
**Pull request by pakarat044**
Create a page for vaccination chart report.

### CODE REVIEW

**Review by PitchapaSaelim — APPROVED** [review]
Perfect chart for vaccination report!

**Review by jeanyjean — APPROVED** [review]
The page is nice and the graph is easy to ready with all the information required.

**Review by ingkharatj — APPROVED** [review]

**Review by PanidaOun — APPROVED** [review]
Nice graph! Very Good.

**Review by nuttapol-kor — APPROVED** [review]
Some fail tests occur from Netlify so I fixed that one. The chart looks nice and fetches (send a request) API from the backend 1 time.

**Review by vnsvakanda — COMMENTED** [review]
The chart is amazing. I love it, nice job!

**Review by vnsvakanda — APPROVED** [review]

**Pull request merged**
